export type ErrorCode =
  | 'AUTHENTICATION_REQUIRED'
  | 'AUTH_SESSION_EXPIRED'
  | 'AUTH_SESSION_REVOKED'
  | 'AUTH_USER_SUSPENDED'
  | 'AUTH_USER_DELETED'
  | 'AUTH_OAUTH_STATE_INVALID'
  | 'AUTH_OAUTH_STATE_EXPIRED'
  | 'AUTH_OAUTH_STATE_USED'
  | 'AUTH_GOOGLE_CALLBACK_FAILED'
  | 'AUTH_GOOGLE_IDENTITY_INVALID'
  | 'AUTH_TUTORIAL_VALIDATION_FAILED'
  | 'GMAIL_PERMISSION_DENIED'
  | 'GMAIL_PERMISSION_INCOMPLETE'
  | 'GMAIL_CONNECTION_FAILED'
  | 'GMAIL_REAUTH_REQUIRED'
  | 'GMAIL_ALREADY_DISCONNECTED'
  | 'GMAIL_ACCOUNT_NOT_CONNECTED'
  | 'GMAIL_ACCOUNT_MISMATCH'
  | 'GMAIL_SYNC_ALREADY_RUNNING'
  | 'GMAIL_INITIAL_SYNC_REQUIRED'
  | 'GMAIL_HISTORY_EXPIRED'
  | 'GMAIL_RATE_LIMITED'
  | 'GMAIL_UPSTREAM_UNAVAILABLE'
  | 'GMAIL_SYNC_FAILED'
  | 'GMAIL_WRITE_DISABLED'
  | 'GMAIL_WRITE_SCOPE_MISSING'
  | 'CLASSIFICATION_DISABLED'
  | 'CLASSIFICATION_PROVIDER_UNAVAILABLE'
  | 'CLASSIFICATION_PROVIDER_TIMEOUT'
  | 'CLASSIFICATION_PROVIDER_RATE_LIMITED'
  | 'CLASSIFICATION_INVALID_RESPONSE'
  | 'CLASSIFICATION_INPUT_TOO_LARGE'
  | 'CLASSIFICATION_ALREADY_RUNNING'
  | 'CLASSIFICATION_MESSAGE_NOT_FOUND'
  | 'CLASSIFICATION_RESULT_NOT_FOUND'
  | 'CLASSIFICATION_NOT_ELIGIBLE'
  | 'CLASSIFICATION_VALIDATION_FAILED'
  | 'CLASSIFICATION_FAILED'
  | 'LABEL_DISCOVERY_ALREADY_RUNNING'
  | 'LABEL_DISCOVERY_DISABLED'
  | 'ACTIVITY_RUN_CONFLICT'
  | 'ACTIVITY_RUN_NOT_FOUND'
  | 'ACTIVITY_VALIDATION_FAILED'
  | 'RUN_ABANDONED'
  | 'LABEL_PLAN_EMPTY'
  | 'LABEL_PLAN_NOT_FOUND'
  | 'LABEL_PLAN_NOT_PENDING'
  | 'LABEL_PLAN_NODE_NOT_FOUND'
  | 'LABEL_LIMIT_REACHED'
  | 'LABEL_GMAIL_CREATION_FAILED'
  | 'LABEL_GMAIL_REAUTH_REQUIRED'
  | 'LABEL_NAME_INVALID'
  | 'LABEL_DUPLICATE'
  | 'LABEL_NOT_FOUND'
  | 'LABEL_SET_EMPTY'
  | 'LABEL_VALIDATION_FAILED'
  | 'LABEL_PROPOSAL_ALREADY_RUNNING'
  | 'LABEL_PROPOSAL_NOT_ENOUGH_MAIL'
  | 'FACET_VOCABULARY_EMPTY'
  | 'FACET_VOCABULARY_NOT_APPROVED'
  | 'AUTOMATION_NO_APPROVED_LABELS'
  | 'AUTOMATION_LABEL_NOT_APPROVED'
  | 'AUTOMATION_ALREADY_RUNNING'
  | 'AUTOMATION_DISABLED'
  | 'AUTOMATION_NOT_CONFIGURED'
  | 'AUTOMATION_ACTION_NOT_FOUND'
  | 'AUTOMATION_ACTION_NOT_REVIEWABLE'
  | 'AUTOMATION_VALIDATION_FAILED'
  | 'FACET_VALIDATION_FAILED'
  | 'AUTOMATION_FAILED'
  | 'PROVIDER_NOT_CONFIGURED'
  | 'PROVIDER_AUTHENTICATION_FAILED'
  | 'PROVIDER_RATE_LIMITED'
  | 'PROVIDER_MODEL_UNAVAILABLE'
  | 'PROVIDER_BAD_REQUEST'
  | 'PROVIDER_INVALID_RESPONSE'
  | 'PROVIDER_UNAVAILABLE'
  | 'RATE_LIMIT_EXCEEDED'
  | 'CORS_ORIGIN_DENIED'
  | 'CSRF_ORIGIN_INVALID'
  | 'DATABASE_UNAVAILABLE'
  | 'INTERNAL_SERVER_ERROR'
  | 'NOT_FOUND';

/**
 * Refusals that come from how this deployment is configured, not from anything going wrong.
 *
 * Each answers 503 because the request genuinely cannot be served, but none is a fault: the
 * operator turned a feature off, or never turned it on, and the screen shows the code so a person
 * can act on it. They are thrown deliberately on a path that expects them.
 *
 * Sentry is told to ignore them. Otherwise every click on a button belonging to a disabled feature
 * files a new issue — and since `GMAIL_WRITE_ENABLED` is off by default, the Gmail export buttons
 * would do it on every press — which buries the faults Sentry exists to surface.
 *
 * Provider failures are deliberately NOT here. `PROVIDER_UNAVAILABLE` means Gemini broke, and that
 * is worth being told about even though it is also a 503.
 */
export const CONFIGURATION_REFUSALS = new Set<ErrorCode>([
  'AUTOMATION_DISABLED',
  'AUTOMATION_NOT_CONFIGURED',
  'CLASSIFICATION_DISABLED',
  'LABEL_DISCOVERY_DISABLED',
  'PROVIDER_NOT_CONFIGURED',
  'GMAIL_WRITE_DISABLED',
]);

export class AppError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly statusCode = 500,
  ) {
    super(message);
    this.name = 'AppError';
  }
}

export const authenticationRequired = () =>
  new AppError('AUTHENTICATION_REQUIRED', 'You need to sign in to continue.', 401);
